name: Test (Post)

on:
  workflow_run:
    workflows: ["Test"]
    types:
    - completed

jobs:
  test-post:
    name: Test (Post)
    runs-on: ubuntu-latest

    steps:
    - name: Print test
      run: |
        echo "${{ toJSON(github.event.workflow_run) }}"
